default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to the Google Play"
  lane :release do
    sh("(cd ../../ && node ./scripts/change-version.js -f)")
    gradle(task: 'bundle', build_type: 'Release')
    upload_to_play_store(track: "alpha", skip_upload_apk: true)
  end
end
